<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>X68</string>
		<string>s</string>
	</array>
	<key>name</key>
	<string>CPU32</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.single.cpu32</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(\*.*$|\;.*$)</string>
			<key>name</key>
			<string>comment.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Data Registers and Address Registers</string>
			<key>match</key>
			<string>\b([dD]|[aA])[0-7]\b</string>
			<key>name</key>
			<string>storage.type.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assembler Directives</string>
			<key>match</key>
			<string>(?i)\b(dc|dcb|ds|endc|endm|textequ|equ|else|elseif|fail|global|ifeq|ifne|include|incbin|list|nolist|macro|memory|mexit|offset|opt|org|page|reg|section|set|simhalt|text)(\.[lLbBwW])?\b</string>
			<key>name</key>
			<string>storage.type.asmdirectives.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Data Movement</string>
			<key>match</key>
			<string>(?i)\b(exg|lea|link|move[ampq]?|pea|swap|unlk)(\.[lLbBwW])?\b</string>
			<key>name</key>
			<string>keyword.control.datamovement.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Integer Arithmetics</string>
			<key>match</key>
			<string>(?i)\b(add[aiqx]?|clr|cmp[aim]?|div[su]?|ext|mul[su]?|neg[x]?|sub[aiqx]?|tas|tst)(\.[lLbBwW])?\b</string>
			<key>name</key>
			<string>keyword.control.integerarithmetic.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Logical Operators</string>
			<key>match</key>
			<string>(?i)\b(and[i]?|or[i]?|eor[i]?|not)(\.[lLbBwW])?\b</string>
			<key>name</key>
			<string>keyword.control.logicaloperators.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Shift and Rotation</string>
			<key>match</key>
			<string>(?i)\b(as[lr]|ls[lr]|ro[lr]|rox[lr])(\.[lLbBwW])?\b</string>
			<key>name</key>
			<string>keyword.control.shiftrotation.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Bit Manipulation</string>
			<key>match</key>
			<string>(?i)\b(btst|bset|bclr|bchg)(\.[lLbBwW])?\b</string>
			<key>name</key>
			<string>keyword.control.bitmanipulation.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Program Control</string>
			<key>match</key>
			<string>(?i)\b(bcc|bcs|beq|bne|bge|bgt|bhi|ble|bls|blt|bmi|bpl|bvc|bvs|bra|bsr|jsr|rts|jmp|rtr)(\.[lLbBwWsS])?\b</string>
			<key>name</key>
			<string>keyword.control.programcontrol.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: System Control and Other</string>
			<key>match</key>
			<string>(?i)\b(reset|rte|stop|chk|trapv|trap|illegal|nop)\b</string>
			<key>name</key>
			<string>keyword.control.shiftrotation.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Labels</string>
			<key>match</key>
			<string>^[A-Za-z0-9_]{2,20}:</string>
			<key>name</key>
			<string>entity.name.function.label.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric Values</string>
			<key>match</key>
			<string>(\#[0-9]*|\#\$[0-9A-Fa-f]*|\#\%[01]*|\$[0-9A-Fa-f]+)</string>
			<key>name</key>
			<string>constant.numeric.cpu32</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cpu32</string>
	<key>uuid</key>
	<string>1ecf7cd0-b930-11e3-a5e2-0800200c9a66</string>
</dict>
</plist>
