<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>X68</string>
	</array>
	<key>name</key>
	<string>CPU32</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(\*.*$|\;.*$)</string>
			<key>name</key>
			<string>comment.cpu32</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.quoted.single.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assembler Directives</string>
			<key>match</key>
			<string>(?i)(dc|dcb|ds|end|equ|fail|include|incbin|list|nolist|memory|offset|opt|org|page|reg|section|set|simhalt)(\.[lLbBwW])?</string>
			<key>name</key>
			<string>storage.type.asmdirectives.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Data Movement</string>
			<key>match</key>
			<string>(?i)(exg|lea|link|move[ampq]?|pea|swap|unlk)(\.[lLbBwW])?</string>
			<key>name</key>
			<string>keyword.control.datamovement.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Integer Arithmetics</string>
			<key>match</key>
			<string>(?i)(add[aiqx]?|clr|cmp[aim]?|div[su]?|ext|mul[su]?|neg[x]?|sub[aiqx]?|tas|tst)(\.[lLbBwW])?</string>
			<key>name</key>
			<string>keyword.control.integerarithmetic.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Logical Operators</string>
			<key>match</key>
			<string>(?i)(and[i]?|or[i]?|eor[i]?|not)(\.[lLbBwW])?</string>
			<key>name</key>
			<string>keyword.control.logicaloperators.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Shift and Rotation</string>
			<key>match</key>
			<string>(?i)(as[lr]|ls[lr]|ro[lr]|rox[lr])(\.[lLbBwW])?</string>
			<key>name</key>
			<string>keyword.control.shiftrotation.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Bit Manipulation</string>
			<key>match</key>
			<string>(?i)(btst|bset|bclr|bchg)(\.[lLbBwW])?</string>
			<key>name</key>
			<string>keyword.control.bitmanipulation.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Program Control</string>
			<key>match</key>
			<string>(?i)(bcc|bcs|beq|bne|bge|bgt|bhi|ble|bls|blt|bmi|bpl|bvc|bvs|bra|bsr|jsr|rts|jmp|rtr)(\.[lLbBwW])?</string>
			<key>name</key>
			<string>keyword.control.programcontrol.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: System Control</string>
			<key>match</key>
			<string>(?i)(reset|rte|stop|chk|trapv|trap)</string>
			<key>name</key>
			<string>keyword.control.shiftrotation.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Instruction Summary: Other</string>
			<key>match</key>
			<string>(?i)(illegal|nop)</string>
			<key>name</key>
			<string>keyword.control.shiftrotation.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Labels</string>
			<key>match</key>
			<string>^[A-Za-z0-9]{2,8}:</string>
			<key>name</key>
			<string>entity.name.function.label.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric Values</string>
			<key>match</key>
			<string>(\#[0-9]*|\#\$[0-9a-f]*|\#\%[01]*|\$[0-9a-f]*)</string>
			<key>name</key>
			<string>constant.numeric.cpu32</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Data Registers and Address Registers</string>
			<key>match</key>
			<string>([dD]|[aA])[0-7]</string>
			<key>name</key>
			<string>storage.type.cpu32</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.cpu32</string>
	<key>uuid</key>
	<string>1ecf7cd0-b930-11e3-a5e2-0800200c9a66</string>
</dict>
</plist>
